# Generated by Django 6.0.5 on 2026-05-30 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScanResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume_filename', models.CharField(max_length=255)),
                ('job_description', models.TextField()),
                ('match_score', models.IntegerField()),
                ('matched_skills', models.JSONField()),
                ('missing_skills', models.JSONField()),
                ('strengths', models.JSONField()),
                ('improvements', models.JSONField()),
                ('summary', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
